package authentication_project.fido.common.exception

class NotFoundChallengeException(message:String): RuntimeException(message) {
}